#React app image
FROM node:20.12.2 AS builder

WORKDIR /app

COPY package*.json ./

RUN npm install

ARG REACT_APP_HOST_IP_ADDRESS

ENV REACT_APP_HOST_IP_ADDRESS $REACT_APP_HOST_IP_ADDRESS

COPY . .

RUN npm run build

FROM nginx:latest as prod

COPY --from=builder /app/build /usr/share/nginx/html
COPY nginx.prod.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
