version: '3'

# networks:
#   express-react:
#     driver: bridge

services:
  react:
    build: ./cash-car-react
    depends_on:
      - express
    # networks:
    #   - express-react
    ports:
      - '80:80'

  express:
    build: ./server
    ports:
      - '5000:5000'
    # networks:
    #   - express-react