version: '3'

services:
  react:
    build: ./cash-car-react
    depends_on:
      - express
    ports:
      - '80:80'
    restart: always

  express:
    build: ./server
    ports:
      - '5000:5000'
    restart: always
